<?php

namespace App\Services\EbayService\Product\Services;
use App\Services\EbayService\Product\Types\AddProductsRequest;
use App\Services\EbayService\Product\Types\FindProductsRequest;
use App\Services\EbayService\Product\Types\GetProductDetailsRequest;
use App\Services\EbayService\Product\Types\GetProductSubmissionsRequest;
use App\Services\EbayService\Product\Types\GetProductCompatibilitiesRequest;
use App\Services\EbayService\Product\Types\FindProductsByCompatibilityRequest;
use App\Services\EbayService\Product\Types\FindCompatibilitiesBySpecificationRequest;

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */


class ProductService extends ProductBaseService
{
    const API_VERSION = '1.4.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param FindProductsRequest $request
     * @return FindProductsResponse
     */
    public function findProducts(FindProductsRequest $request)
    {
        return $this->findProductsAsync($request)->wait();
    }

    /**
     * @param \App\Services\EbayService\Product\Types\FindProductsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findProductsAsync(FindProductsRequest $request)
    {
        return $this->callOperationAsync(
            'findProducts',
            $request,
            '\App\Services\EbayService\Product\Types\FindProductsResponse'
        );
    }

    /**
     * @param \App\Services\EbayService\Product\Types\FindProductsByCompatibilityRequest $request
     * @return \App\Services\EbayService\Product\Types\FindProductsResponse
     */
    public function findProductsByCompatibility(FindProductsByCompatibilityRequest $request)
    {
        return $this->findProductsByCompatibilityAsync($request)->wait();
    }

    /**
     * @param \App\Services\EbayService\Product\Types\FindProductsByCompatibilityRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findProductsByCompatibilityAsync(FindProductsByCompatibilityRequest $request)
    {
        return $this->callOperationAsync(
            'findProductsByCompatibility',
            $request,
            '\App\Services\EbayService\Product\Types\FindProductsResponse'
        );
    }

    /**
     * @param \App\Services\EbayService\Product\Types\GetProductDetailsRequest $request
     * @return \App\Services\EbayService\Product\Types\GetProductDetailsResponse
     */
    public function getProductDetails(GetProductDetailsRequest $request)
    {
        return $this->getProductDetailsAsync($request)->wait();
    }

    /**
     * @param \App\Services\EbayService\Product\Types\GetProductDetailsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductDetailsAsync(GetProductDetailsRequest $request)
    {
        return $this->callOperationAsync(
            'getProductDetails',
            $request,
            '\App\Services\EbayService\Product\Types\GetProductDetailsResponse'
        );
    }

    /**
     * @param \App\Services\EbayService\Product\Types\GetProductCompatibilitiesRequest $request
     * @return \App\Services\EbayService\Product\Types\GetProductCompatiblitiesResponse
     */
    public function getProductCompatibilities(GetProductCompatibilitiesRequest $request)
    {
        return $this->getProductCompatibilitiesAsync($request)->wait();
    }

    /**
     * @param \App\Services\EbayService\Product\Types\GetProductCompatibilitiesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductCompatibilitiesAsync(GetProductCompatibilitiesRequest $request)
    {
        return $this->callOperationAsync(
            'getProductCompatibilities',
            $request,
            '\App\Services\EbayService\Product\Types\GetProductCompatiblitiesResponse'
        );
    }

    /**
     * @param \App\Services\EbayService\Product\Types\FindCompatibilitiesBySpecificationRequest $request
     * @return \App\Services\EbayService\Product\Types\FindCompatibilitiesBySpecificationResponse
     */
    public function findCompatibilitiesBySpecification(FindCompatibilitiesBySpecificationRequest $request)
    {
        return $this->findCompatibilitiesBySpecificationAsync($request)->wait();
    }

    /**
     * @param \App\Services\EbayService\Product\Types\FindCompatibilitiesBySpecificationRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findCompatibilitiesBySpecificationAsync(FindCompatibilitiesBySpecificationRequest $request)
    {
        return $this->callOperationAsync(
            'findCompatibilitiesBySpecification',
            $request,
            '\App\Services\EbayService\Product\Types\FindCompatibilitiesBySpecificationResponse'
        );
    }

    /**
     * @param \App\Services\EbayService\Product\Types\AddProductsRequest $request
     * @return \App\Services\EbayService\Product\Types\AddProductsResponse
     */
    public function addProducts(AddProductsRequest $request)
    {
        return $this->addProductsAsync($request)->wait();
    }

    /**
     * @param \App\Services\EbayService\Product\Types\AddProductsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addProductsAsync(AddProductsRequest $request)
    {
        return $this->callOperationAsync(
            'addProducts',
            $request,
            '\App\Services\EbayService\Product\Types\AddProductsResponse'
        );
    }

    /**
     * @param \App\Services\EbayService\Product\Types\GetProductSubmissionsRequest $request
     * @return \App\Services\EbayService\Product\Types\GetProductSubmissionsResponse
     */
    public function getProductSubmissions(GetProductSubmissionsRequest $request)
    {
        return $this->getProductSubmissionsAsync($request)->wait();
    }

    /**
     * @param \App\Services\EbayService\Product\Types\GetProductSubmissionsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSubmissionsAsync(GetProductSubmissionsRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSubmissions',
            $request,
            '\App\Services\EbayService\Product\Types\GetProductSubmissionsResponse'
        );
    }
}
