<?php

/**
 * Configuration settings used by all of the examples.
 *
 * Specify your eBay application keys in the appropriate places.
 *
 * Be careful not to commit this file into an SCM repository.
 * You risk exposing your eBay application keys to more people than intended.
 */
return [

  // get form ebay sites
  'environment'         => false,
  'debug'              => false,
  'compatabilityLevel' => 681,
  'findingVer'         => '1.8.0',
  'siteID'             => 0,
  
  // Sandbox (Test) Environment
  'sandbox' => [
    // credentials
    'devID'       => '3485ac97-486f-409c-888e-7c058a9c4010',             // insert your devID for sandbox
    'client_id'       => 'AAwalHad-FullStro-SBX-df492a7b2-67d99ce2',    // appID, client_id and clientID same
    'client_secret'      => 'SBX-f48985aef73e-419c-46c8-9869-7296',      // certID, client_secret  same// 
    'redirect_uri' => "fullstro_Invent-AAwalHad-FullSt-bhqckh",  // app runnane
    'auth_url'    => 'https://auth.sandbox.ebay.com',    // sandbox auth url
    'api_url'    => 'https://api.sandbox.ebay.com',       // sandbox api_url

    // tokens
    'consent_token' => 'v^1.1#i^1#f^0#r^1#I^3#p^3#t^Ul41XzI6RkY0NjNDNUUyMUQ5Mzk0ODZDQUU0MDk1MEQ1QTcwMkFfMF8xI0VeMTI4NA==',
     // refresh token
     'refresh_token'            => 'v^1.1#i^1#r^1#I^3#p^3#f^0#t^Ul4xMF84OkE2M0JDRUVBMTIxQUJGRDM4MDQxN0IzNTRENkU0NkM5XzNfMSNFXjEyODQ=',
     'refresh_token_expires_in' => '47304000',
     'refresh_token_created_at' => '',
       // user access token
     'user_access_token' => 'v^1.1#i^1#f^0#r^0#I^3#p^3#t^H4sIAAAAAAAAAOVZf2gb1x2P4h/F5EdH13XpZoJza9gyc9LT3enHXWtvsi3HcuOfUlTX2zBP795ZLz7dne+9s61QhklCaJqylUHW0q4QNhgbzaCFFZqObJQmoWUUAmkhZFDYr1KWsvaftgsjY+8kW5G1NbGkQsQmjKX37vvr8/317r0HVju7vnl85PinOwJ3bT29Cla3BgLhbaCrs6N3Z9vWr3RsAVUEgdOrD6y2H2l7/yEKC6ajTWPq2BbFPSsF06JaabJP8FxLsyElVLNgAVONIS2dGDugSUGgOa7NbGSbQk9qqE+AEEqGhAxo5DCIxCJ81lqXmbH7hAiKwFxYVuUYzClRRefPKfVwyqIMWqxPkIAki2FJlGIZENEUoEXkIFCkWaEni11KbIuTBIHQXzJXK/G6Vbbe2lRIKXYZFyL0pxLD6YlEaig5nnkoVCWrf80PaQaZRzeOBm0d92Sh6eFbq6Elai3tIYQpFUL9ZQ0bhWqJdWMaML/s6jhQIwBEdcidinXwubhy2HYLkN3aDn+G6KJRItWwxQgr3s6j3Bu5QxixtdE4F5Ea6vG/pjxoEoNgt09IDiQePZhOTgs96clJ114iOtZ9pGFZkdWwokaFfoYpdyF25+AyNPNQJ2u6ygLXPF2jbNC2dOL7jfaM22wAc8NxrXvkKvdwoglrwk0YzDeqmi627kY5PuvHtRxIj+UtP7S4wH3RUxrePgjrWXEzDz6vvIgjkIuH41EjipAhGerGvPBrvbHc6PfDk5icDPm24BwsigXoLmDmmBBhEXH3egXsEl2TI4Ykxw0s6lHVEBXVMMRcRI+KYQNjgHEuh9T4/1mKMOaSnMdwJU1qH5Rw9glpZDt40jYJKgq1JKXOs5YUK7RPyDPmaKHQ8vJycFkO2u58SAIgHJoZO5BGeVyAQoWW3J5YJKX0QJhzUaKxosOtWeHZx5Vb80K/7OqT0GXFAa/Ix2lsmvxrPYM3WNhfO/sZUAdNwv2Q4YpaC+mITRnWm4Km4yWC8BzR7zAyv9Zr0InhppCZ9jyxxjDL23caWw0uvyekhprCxlsoZK2FqtJYohlJWm9AfMy7DABNgU04TqpQ8BjMmTjVYrFUwpIUizQFz/G8O159NajURaK4RVRk7mJT0PyVVyPQ0Ji9gK1K//RrvWWwTieHp5PpkbnMxMPJ8abQTmPDxTSf8bG2Wp4mphLJBP+M7V8BjExBnF3Ij5CVbCaSGXCkwyCUHcnOEpTszXiLcHS/SWg+fnBoPCvn8bh7AB1GOnl4MAFmyVRfX1NOSmPk4hZrXQNxMig/MhnqJWBw1Nk/zf/hRYO6y3JsURkfTQ0uTcwcGB0zUlRpDnxmQxm0DH63nLhzpSqd46OmQCbnq/uZX+stARKqas7gf2G+54CKoksxCcvxmG4Yhm6oRrzpJarVKj7BtxQjUBeHPdNMM9cW0wMzom4oqgRjOUmMxnRVRVhqcu36X126qL+7aS1oPj/lAqBDgv7KGkR2IWRDvof3p+ZKFvdshiiU84pcv47doIuhbltmcfN88x7fs5a5a5n8Wv/vjJRvwoLlLTiHUqfWjcx18BBriW/bbLfYiMIKcx08ECHbs1gj6tZY6+AwPNMgpunv0BtRWMVej5kWNIuMINp4DEtnMNy9lMznWb1y+FwBu5wfQQb5Dq+BBKZ523H8LETQ3ST0Ur0YBq8X6KHSeVd9xhK9fPLYKNgKP+8SxGxaipO3LdyklHKtQ13nbw4NB7FikX9Q2LSQ8ll2Q7VALL/v0jpYHFgsVZ5OqOOvGnU0FoYLQd2FRj115zPVQe5ibhTcfKbWMDUaCstmxCCoLIN6OYpc4jRQL58pp5HgUt7E6wptmaGiqrmDGqwTFyM257mktd4meP83+W97LlVa6MSa90Uxl19EC/kSTF7rdzXqAN/BrXgIN5lIpx+ZmG7uGG4IL7Xaa7+sxCMQqTFRiUcNUQEqEuPxOBZjCETiUEUKCDd3GtdyB4/hGJCjkUg0sunj4pqJqouO/7jmCm28au7fUvqEjwTOgSOBs1sDARADYrgX7OtsO9jetl2gvFEHKbT0nL0SJNAI8rcciy9LLg4u4KIDibu1M0Cuvo3+UXXJffp7YFflmrurLbyt6s4bdN980hG++8s7JNk/cgQRBUTkWfC1m0/bw/e137vz2Ilu5c23Tt54Y6b33Sf//DPBPL8H7KgQBQIdW9qPBLbI9xzT8++9NbXn7398nuzt+ML9T3zwo6f/ie9/qXPkxf0//NVPadB68Gr21Y/+8qx1/V/dT7LE6NWOCy8/tV298rHz/IVPrxzNXX5s1/XTp45PBRaemNn+0YVPjNfmf73XunTlhdBf73lh90uHVhJv/uCrJ/8WetQ5+2x3dO8b2o/PDT/4+ntPPfbud+/+ZHd26u2F69cef/0nj1/7zscnztDAfU8H3z90LHR+39cvfeMUCb9z/sb10YvZ1ece2DOy+8TJXyxg+s6HVtvZc5e+1fX7Z145Mwr2/UZ45U+HlWvbdn5RujGdZ0cv7vN+OXXq5Z/Hn9mx6+pvT37w/df+IL86fW96Z3v/c1cu/e7DM19SL1882nXj8rdf7E6Ww/hvLCao4X4gAAA=',
     'expires_in'        => '7200',
     'created_at'        => '',

    //  access token
    'access_token' => 'v^1.1#i^1#f^0#r^0#I^3#p^3#t^H4sIAAAAAAAAAOVZe2wbdx2P8ypVSdGgdNM2bZY7bYLq7HvZvrsuVp1HG4c83NhN20AVfv7d7+xfc767/O53cTzYFAJMjCGQpqpMlSYVbaAhlWkgyigbmzrxR1UxJljFH/sDKTyksaLx0ApFPMTv7DR1jNrE9kSsYUWx73ff1+f7+r34pd7tH3905NG/9QW2dZ5Z4pc6AwFhB7+9t2fvzq7OO3s6+BqCwJml+5a6l7veetAFRdPRppDr2JaLgotF03K1ymB/yCOWZgMXu5oFisjVKNQyyfExTQzzmkNsakPbDAVTQ/2hOIKGwgM5pupAFaHBRq3rMrN2fyiGBBnoUUMy4giIcYG9d10PpSyXAov2h0RelDhB5MR4llc0OabJajgqx2ZCwWlEXGxbjCTMhxIVc7UKL6mx9damAtdFhDIhoUQqeSAzmUwNDU9kH4zUyEqs+iFDAfXc9U+Dto6C08D00K3VuBVqLeNBiFw3FElUNawXqiWvG9OE+RVXq6KQk2ISD6MxXQYAvSeuPGCTIqC3tsMfwTpnVEg1ZFFMyxt5lHkjdwJBuvo0wUSkhoL+1yEPmNjAiPSHhgeSxw5nhqdCwUw6TewFrCPdRypIsqQKshoLJShymQsRmQUlYBaAjld1VQWuerpO2aBt6dj3mxucsOkAYoajevdINe5hRJPWJEka1Deqhk7g19wozvhxrQbSowXLDy0qMl8EK48bB+F6VtzIg/cqLwxFgQIwRKDwkiFKsfV54dd6c7mR8MOTTKcjvi0oB8pcEZA5RB0TQMRB5l6viAjWNSnK1CoG4vSYanCyahhcLqrHOMFAiEcol4Oq8n+WIpQSnPMoWkuT+hcVnP2hDLQdlLZNDMuhepJK51lNikW3P1Sg1NEikVKpFC5JYZvkIyLPC5Gj42MZWEBFEFqjxRsTc7iSHpB1EUav0bLDrFlk2ceUW/lQQiJ6GhBaHvDK7DmDTJN9Xc/gdRYm6kdvAnXQxMwPWaaovZCO2C5FekvQdLSAIZrF+hYj82u9Dh0ntITMtPPYGke0YG81tjpcfk9IDbWEjbVQQNsLlRDnpVg0rsjRlpAlHSdVLHoU5EyUarPAyYIoxluD53jelpdaHSp1HsukDMuUzLcEzZ9mNQwMjdpzyLpVs/RrfWuwTg0fmBrOjMxmJz8xPNES2ilkEOQWsj7WdsvT5KHkcJJ9xodmlPwUkkhqfiEDo/GUky+Z5fwQmgNqMpo/NFQ6puTVo0mwEFOPTS0m+RjVgXNiXhyBOfngTHq01N/fkpMyCBLUZn1qQMGD0pF0ZC/mB0edg1PsH5o3XFKS4vPyxGhqcGHy6NjouJFy5dbAZzcqg63BT6qJO1up0ln21BLI4fwG/cyv9f89SKCqOYP9CQpkG3xZF+MikpS4bhiGbqiG0vIU1W4Vn2T7hxGgcwc808xQYnOZgaOcbsiqCOI5kYvFdVWFSGxx7nq/Tl2uv5VpL2g+v8sEAAeH/Zk1DO1ixAZsw+4PzVYsDm6GKJLzyky/jkiYIKDbllnePF/eYxvUKvcmmKpr+IjLdlzh6n6bQWlQ63rmBniwtcD2aDYpN6NwjbkBHgCh7Vm0GXWrrA1wGJ5pYNP0t+PNKKxhb8RMC5hliqHbfAwrBy7MvS7OF2ijcthYERHGDwEFbDvXRAK7Bdtx/CyEgGwSeqVeDIPVC/Bg5XCrMWOxXj1mbBbsGj/rEthsWYpTsC3UshSg62zVUBNAv9ablOWfCrZsUPXguqlawJbfd90GWBxQrlSejl3HnzUaaCwUFcM6AUYjdeczNUBOEDMKbD5T65iaDYVlU2xgWJXhejkXEuw0US83ldNMcF3WxBsKbZVhTVVrpzJIxwRBOusR3F6rCdb/Tfbbnk1VJjqubr3I5QrzcK5wM/Ddy53vbsoBvoPb8cQtncxkjkxOtXbmNoQW2m3ZL8lKFEA1zslKzOBkXoWcoiiIi0M+qgAVyrzAt4T5fXDKWDdQc6vxX3dakfX3yomOykdYDvyYXw6c7wwE+DjPCXv5j/V2He7u+mDIZY067AJLz9mLYQyMMFvlWGxaIig8h8oOwKSzN4DfvAyv1dxonznO37F2p729S9hRc8HN333jTY/wodv7RMk/cuQVOSarM/yeG2+7hd3du8alS9+9+vztf7p3D+wyVrIfzp6/+g2+b40oEOjp6F4OdBy672z2idinXpDvPWBH3v22+MKLfznz+697F1+J/+zZg7/tsQ9f/OeTavrnP93/r56nfvj9bSe/9YeVgZN/PvvUqYHntl187IHtwrR1rXxhdOV0IvjE4G37dw5efkZ+e+n4iX8/dGrirZXXlvbt+PViMbP8xoTQk332i5fGzr5y7cKduX193AM7u0vHu994/fQXLn/5q+i5y+fGPnBlkN83/bXz3GRf4eHFlz7yzcdfPrnr+MOf/uOVKy/f9smlnr+f+sc78edf2n3h7s9Z4595ZP7w07977ZFXd73+zi9+86vT3zv3eXJu21dm6elf7u7Yf/9DpWLv1cUv3fXRH8399Y7wDjt3z11zV9+8/+1XL93zg8fDT774nT3T2c8eWXnsJ9Uw/gdlAPeYayAAAA==',


    // scopes
    'scopes' => "https://api.ebay.com/oauth/api_scope https://api.ebay.com/oauth/api_scope/buy.order.readonly https://api.ebay.com/oauth/api_scope/buy.guest.order https://api.ebay.com/oauth/api_scope/sell.marketing.readonly https://api.ebay.com/oauth/api_scope/sell.marketing https://api.ebay.com/oauth/api_scope/sell.inventory.readonly https://api.ebay.com/oauth/api_scope/sell.inventory https://api.ebay.com/oauth/api_scope/sell.account.readonly https://api.ebay.com/oauth/api_scope/sell.account https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly https://api.ebay.com/oauth/api_scope/sell.fulfillment https://api.ebay.com/oauth/api_scope/sell.analytics.readonly https://api.ebay.com/oauth/api_scope/sell.marketplace.insights.readonly https://api.ebay.com/oauth/api_scope/commerce.catalog.readonly https://api.ebay.com/oauth/api_scope/buy.shopping.cart https://api.ebay.com/oauth/api_scope/buy.offer.auction https://api.ebay.com/oauth/api_scope/commerce.identity.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.email.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.phone.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.address.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.name.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.status.readonly https://api.ebay.com/oauth/api_scope/sell.finances https://api.ebay.com/oauth/api_scope/sell.payment.dispute https://api.ebay.com/oauth/api_scope/sell.item.draft https://api.ebay.com/oauth/api_scope/sell.item https://api.ebay.com/oauth/api_scope/sell.reputation https://api.ebay.com/oauth/api_scope/sell.reputation.readonly https://api.ebay.com/oauth/api_scope/commerce.notification.subscription https://api.ebay.com/oauth/api_scope/commerce.notification.subscription.readonly https://api.ebay.com/oauth/api_scope/sell.stores https://api.ebay.com/oauth/api_scope/sell.stores.readonly",
  ],

  // Production Environment
  'production' => [
    // credentials
    'devID'         => '',                                           // these prod keys are different from sandbox keys
    'client_id'     => 'AAwalHad-FullStro-SBX-df492a7b2-67d99ce2',   // appID and clientID same
    'client_secret' => 'SBX-f48985aef73e-419c-46c8-9869-7296',       // certID, client_secret  same// 
    'redirect_uri'  => "fullstro_Invent-AAwalHad-FullSt-bhqckh",     // app runnane
    'auth_url'      => 'https://auth.ebay.com',                      // production auth url
    'api_url'       => 'https://api.ebay.com',                       // production api_url

      // tokens
    'consent_token' => 'v^1.1#i^1#f^0#r^1#I^3#p^3#t^Ul41XzI6RkY0NjNDNUUyMUQ5Mzk0ODZDQUU0MDk1MEQ1QTcwMkFfMF8xI0VeMTI4NA==',
      // refresh token
    'refresh_token'            => 'v^1.1#i^1#r^1#I^3#p^3#f^0#t^Ul4xMF84OkE2M0JDRUVBMTIxQUJGRDM4MDQxN0IzNTRENkU0NkM5XzNfMSNFXjEyODQ=',
    'refresh_token_expires_in' => '47304000',
    'refresh_token_created_at' => '',
        // user access token
    'user_access_token' => 'v^1.1#i^1#f^0#r^0#I^3#p^3#t^H4sIAAAAAAAAAOVZf2gb1x2P4h/F5EdH13XpZoJza9gyc9LT3enHXWtvsi3HcuOfUlTX2zBP795ZLz7dne+9s61QhklCaJqylUHW0q4QNhgbzaCFFZqObJQmoWUUAmkhZFDYr1KWsvaftgsjY+8kW5G1NbGkQsQmjKX37vvr8/317r0HVju7vnl85PinOwJ3bT29Cla3BgLhbaCrs6N3Z9vWr3RsAVUEgdOrD6y2H2l7/yEKC6ajTWPq2BbFPSsF06JaabJP8FxLsyElVLNgAVONIS2dGDugSUGgOa7NbGSbQk9qqE+AEEqGhAxo5DCIxCJ81lqXmbH7hAiKwFxYVuUYzClRRefPKfVwyqIMWqxPkIAki2FJlGIZENEUoEXkIFCkWaEni11KbIuTBIHQXzJXK/G6Vbbe2lRIKXYZFyL0pxLD6YlEaig5nnkoVCWrf80PaQaZRzeOBm0d92Sh6eFbq6Elai3tIYQpFUL9ZQ0bhWqJdWMaML/s6jhQIwBEdcidinXwubhy2HYLkN3aDn+G6KJRItWwxQgr3s6j3Bu5QxixtdE4F5Ea6vG/pjxoEoNgt09IDiQePZhOTgs96clJ114iOtZ9pGFZkdWwokaFfoYpdyF25+AyNPNQJ2u6ygLXPF2jbNC2dOL7jfaM22wAc8NxrXvkKvdwoglrwk0YzDeqmi627kY5PuvHtRxIj+UtP7S4wH3RUxrePgjrWXEzDz6vvIgjkIuH41EjipAhGerGvPBrvbHc6PfDk5icDPm24BwsigXoLmDmmBBhEXH3egXsEl2TI4Ykxw0s6lHVEBXVMMRcRI+KYQNjgHEuh9T4/1mKMOaSnMdwJU1qH5Rw9glpZDt40jYJKgq1JKXOs5YUK7RPyDPmaKHQ8vJycFkO2u58SAIgHJoZO5BGeVyAQoWW3J5YJKX0QJhzUaKxosOtWeHZx5Vb80K/7OqT0GXFAa/Ix2lsmvxrPYM3WNhfO/sZUAdNwv2Q4YpaC+mITRnWm4Km4yWC8BzR7zAyv9Zr0InhppCZ9jyxxjDL23caWw0uvyekhprCxlsoZK2FqtJYohlJWm9AfMy7DABNgU04TqpQ8BjMmTjVYrFUwpIUizQFz/G8O159NajURaK4RVRk7mJT0PyVVyPQ0Ji9gK1K//RrvWWwTieHp5PpkbnMxMPJ8abQTmPDxTSf8bG2Wp4mphLJBP+M7V8BjExBnF3Ij5CVbCaSGXCkwyCUHcnOEpTszXiLcHS/SWg+fnBoPCvn8bh7AB1GOnl4MAFmyVRfX1NOSmPk4hZrXQNxMig/MhnqJWBw1Nk/zf/hRYO6y3JsURkfTQ0uTcwcGB0zUlRpDnxmQxm0DH63nLhzpSqd46OmQCbnq/uZX+stARKqas7gf2G+54CKoksxCcvxmG4Yhm6oRrzpJarVKj7BtxQjUBeHPdNMM9cW0wMzom4oqgRjOUmMxnRVRVhqcu36X126qL+7aS1oPj/lAqBDgv7KGkR2IWRDvof3p+ZKFvdshiiU84pcv47doIuhbltmcfN88x7fs5a5a5n8Wv/vjJRvwoLlLTiHUqfWjcx18BBriW/bbLfYiMIKcx08ECHbs1gj6tZY6+AwPNMgpunv0BtRWMVej5kWNIuMINp4DEtnMNy9lMznWb1y+FwBu5wfQQb5Dq+BBKZ523H8LETQ3ST0Ur0YBq8X6KHSeVd9xhK9fPLYKNgKP+8SxGxaipO3LdyklHKtQ13nbw4NB7FikX9Q2LSQ8ll2Q7VALL/v0jpYHFgsVZ5OqOOvGnU0FoYLQd2FRj115zPVQe5ibhTcfKbWMDUaCstmxCCoLIN6OYpc4jRQL58pp5HgUt7E6wptmaGiqrmDGqwTFyM257mktd4meP83+W97LlVa6MSa90Uxl19EC/kSTF7rdzXqAN/BrXgIN5lIpx+ZmG7uGG4IL7Xaa7+sxCMQqTFRiUcNUQEqEuPxOBZjCETiUEUKCDd3GtdyB4/hGJCjkUg0sunj4pqJqouO/7jmCm28au7fUvqEjwTOgSOBs1sDARADYrgX7OtsO9jetl2gvFEHKbT0nL0SJNAI8rcciy9LLg4u4KIDibu1M0Cuvo3+UXXJffp7YFflmrurLbyt6s4bdN980hG++8s7JNk/cgQRBUTkWfC1m0/bw/e137vz2Ilu5c23Tt54Y6b33Sf//DPBPL8H7KgQBQIdW9qPBLbI9xzT8++9NbXn7398nuzt+ML9T3zwo6f/ie9/qXPkxf0//NVPadB68Gr21Y/+8qx1/V/dT7LE6NWOCy8/tV298rHz/IVPrxzNXX5s1/XTp45PBRaemNn+0YVPjNfmf73XunTlhdBf73lh90uHVhJv/uCrJ/8WetQ5+2x3dO8b2o/PDT/4+ntPPfbud+/+ZHd26u2F69cef/0nj1/7zscnztDAfU8H3z90LHR+39cvfeMUCb9z/sb10YvZ1ece2DOy+8TJXyxg+s6HVtvZc5e+1fX7Z145Mwr2/UZ45U+HlWvbdn5RujGdZ0cv7vN+OXXq5Z/Hn9mx6+pvT37w/df+IL86fW96Z3v/c1cu/e7DM19SL1882nXj8rdf7E6Ww/hvLCao4X4gAAA=',
    'expires_in'        => '7200',
    'created_at'        => '',

      //  access token
    'access_token'      => 'v^1.1#i^1#f^0#r^0#I^3#p^3#t^H4sIAAAAAAAAAOVZe2wbdx2P8ypVSdGgdNM2bZY7bYLq7HvZvrsuVp1HG4c83NhN20AVfv7d7+xfc767/O53cTzYFAJMjCGQpqpMlSYVbaAhlWkgyigbmzrxR1UxJljFH/sDKTyksaLx0ApFPMTv7DR1jNrE9kSsYUWx73ff1+f7+r34pd7tH3905NG/9QW2dZ5Z4pc6AwFhB7+9t2fvzq7OO3s6+BqCwJml+5a6l7veetAFRdPRppDr2JaLgotF03K1ymB/yCOWZgMXu5oFisjVKNQyyfExTQzzmkNsakPbDAVTQ/2hOIKGwgM5pupAFaHBRq3rMrN2fyiGBBnoUUMy4giIcYG9d10PpSyXAov2h0RelDhB5MR4llc0OabJajgqx2ZCwWlEXGxbjCTMhxIVc7UKL6mx9damAtdFhDIhoUQqeSAzmUwNDU9kH4zUyEqs+iFDAfXc9U+Dto6C08D00K3VuBVqLeNBiFw3FElUNawXqiWvG9OE+RVXq6KQk2ISD6MxXQYAvSeuPGCTIqC3tsMfwTpnVEg1ZFFMyxt5lHkjdwJBuvo0wUSkhoL+1yEPmNjAiPSHhgeSxw5nhqdCwUw6TewFrCPdRypIsqQKshoLJShymQsRmQUlYBaAjld1VQWuerpO2aBt6dj3mxucsOkAYoajevdINe5hRJPWJEka1Deqhk7g19wozvhxrQbSowXLDy0qMl8EK48bB+F6VtzIg/cqLwxFgQIwRKDwkiFKsfV54dd6c7mR8MOTTKcjvi0oB8pcEZA5RB0TQMRB5l6viAjWNSnK1CoG4vSYanCyahhcLqrHOMFAiEcol4Oq8n+WIpQSnPMoWkuT+hcVnP2hDLQdlLZNDMuhepJK51lNikW3P1Sg1NEikVKpFC5JYZvkIyLPC5Gj42MZWEBFEFqjxRsTc7iSHpB1EUav0bLDrFlk2ceUW/lQQiJ6GhBaHvDK7DmDTJN9Xc/gdRYm6kdvAnXQxMwPWaaovZCO2C5FekvQdLSAIZrF+hYj82u9Dh0ntITMtPPYGke0YG81tjpcfk9IDbWEjbVQQNsLlRDnpVg0rsjRlpAlHSdVLHoU5EyUarPAyYIoxluD53jelpdaHSp1HsukDMuUzLcEzZ9mNQwMjdpzyLpVs/RrfWuwTg0fmBrOjMxmJz8xPNES2ilkEOQWsj7WdsvT5KHkcJJ9xodmlPwUkkhqfiEDo/GUky+Z5fwQmgNqMpo/NFQ6puTVo0mwEFOPTS0m+RjVgXNiXhyBOfngTHq01N/fkpMyCBLUZn1qQMGD0pF0ZC/mB0edg1PsH5o3XFKS4vPyxGhqcGHy6NjouJFy5dbAZzcqg63BT6qJO1up0ln21BLI4fwG/cyv9f89SKCqOYP9CQpkG3xZF+MikpS4bhiGbqiG0vIU1W4Vn2T7hxGgcwc808xQYnOZgaOcbsiqCOI5kYvFdVWFSGxx7nq/Tl2uv5VpL2g+v8sEAAeH/Zk1DO1ixAZsw+4PzVYsDm6GKJLzyky/jkiYIKDbllnePF/eYxvUKvcmmKpr+IjLdlzh6n6bQWlQ63rmBniwtcD2aDYpN6NwjbkBHgCh7Vm0GXWrrA1wGJ5pYNP0t+PNKKxhb8RMC5hliqHbfAwrBy7MvS7OF2ijcthYERHGDwEFbDvXRAK7Bdtx/CyEgGwSeqVeDIPVC/Bg5XCrMWOxXj1mbBbsGj/rEthsWYpTsC3UshSg62zVUBNAv9ablOWfCrZsUPXguqlawJbfd90GWBxQrlSejl3HnzUaaCwUFcM6AUYjdeczNUBOEDMKbD5T65iaDYVlU2xgWJXhejkXEuw0US83ldNMcF3WxBsKbZVhTVVrpzJIxwRBOusR3F6rCdb/Tfbbnk1VJjqubr3I5QrzcK5wM/Ddy53vbsoBvoPb8cQtncxkjkxOtXbmNoQW2m3ZL8lKFEA1zslKzOBkXoWcoiiIi0M+qgAVyrzAt4T5fXDKWDdQc6vxX3dakfX3yomOykdYDvyYXw6c7wwE+DjPCXv5j/V2He7u+mDIZY067AJLz9mLYQyMMFvlWGxaIig8h8oOwKSzN4DfvAyv1dxonznO37F2p729S9hRc8HN333jTY/wodv7RMk/cuQVOSarM/yeG2+7hd3du8alS9+9+vztf7p3D+wyVrIfzp6/+g2+b40oEOjp6F4OdBy672z2idinXpDvPWBH3v22+MKLfznz+697F1+J/+zZg7/tsQ9f/OeTavrnP93/r56nfvj9bSe/9YeVgZN/PvvUqYHntl187IHtwrR1rXxhdOV0IvjE4G37dw5efkZ+e+n4iX8/dGrirZXXlvbt+PViMbP8xoTQk332i5fGzr5y7cKduX193AM7u0vHu994/fQXLn/5q+i5y+fGPnBlkN83/bXz3GRf4eHFlz7yzcdfPrnr+MOf/uOVKy/f9smlnr+f+sc78edf2n3h7s9Z4595ZP7w07977ZFXd73+zi9+86vT3zv3eXJu21dm6elf7u7Yf/9DpWLv1cUv3fXRH8399Y7wDjt3z11zV9+8/+1XL93zg8fDT774nT3T2c8eWXnsJ9Uw/gdlAPeYayAAAA==',

    // scopes
    'scopes' => "https://api.ebay.com/oauth/api_scope https://api.ebay.com/oauth/api_scope/buy.order.readonly https://api.ebay.com/oauth/api_scope/buy.guest.order https://api.ebay.com/oauth/api_scope/sell.marketing.readonly https://api.ebay.com/oauth/api_scope/sell.marketing https://api.ebay.com/oauth/api_scope/sell.inventory.readonly https://api.ebay.com/oauth/api_scope/sell.inventory https://api.ebay.com/oauth/api_scope/sell.account.readonly https://api.ebay.com/oauth/api_scope/sell.account https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly https://api.ebay.com/oauth/api_scope/sell.fulfillment https://api.ebay.com/oauth/api_scope/sell.analytics.readonly https://api.ebay.com/oauth/api_scope/sell.marketplace.insights.readonly https://api.ebay.com/oauth/api_scope/commerce.catalog.readonly https://api.ebay.com/oauth/api_scope/buy.shopping.cart https://api.ebay.com/oauth/api_scope/buy.offer.auction https://api.ebay.com/oauth/api_scope/commerce.identity.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.email.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.phone.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.address.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.name.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.status.readonly https://api.ebay.com/oauth/api_scope/sell.finances https://api.ebay.com/oauth/api_scope/sell.payment.dispute https://api.ebay.com/oauth/api_scope/sell.item.draft https://api.ebay.com/oauth/api_scope/sell.item https://api.ebay.com/oauth/api_scope/sell.reputation https://api.ebay.com/oauth/api_scope/sell.reputation.readonly https://api.ebay.com/oauth/api_scope/commerce.notification.subscription https://api.ebay.com/oauth/api_scope/commerce.notification.subscription.readonly https://api.ebay.com/oauth/api_scope/sell.stores https://api.ebay.com/oauth/api_scope/sell.stores.readonly",
    // 'scopes' => "https://api.ebay.com/oauth/api_scope%20https://api.ebay.com/oauth/api_scope/sell.marketing.readonly%20https://api.ebay.com/oauth/api_scope/sell.marketing%20https://api.ebay.com/oauth/api_scope/sell.inventory.readonly%20https://api.ebay.com/oauth/api_scope/sell.inventory%20https://api.ebay.com/oauth/api_scope/sell.account.readonly%20https://api.ebay.com/oauth/api_scope/sell.account%20https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly%20https://api.ebay.com/oauth/api_scope/sell.fulfillment%20https://api.ebay.com/oauth/api_scope/sell.analytics.readonly%20https://api.ebay.com/oauth/api_scope/sell.finances%20https://api.ebay.com/oauth/api_scope/sell.payment.dispute%20https://api.ebay.com/oauth/api_scope/commerce.identity.readonly",
  ],


  
  

];


// sandbox scops
// https://auth.sandbox.ebay.com/oauth2/authorize?client_id=AAwalHad-FullStro-SBX-df492a7b2-67d99ce2&response_type=code&redirect_uri=A_Awal_Hadi-AAwalHad-FullSt-eqogkgt&scope=https://api.ebay.com/oauth/api_scope https://api.ebay.com/oauth/api_scope/buy.order.readonly https://api.ebay.com/oauth/api_scope/buy.guest.order https://api.ebay.com/oauth/api_scope/sell.marketing.readonly https://api.ebay.com/oauth/api_scope/sell.marketing https://api.ebay.com/oauth/api_scope/sell.inventory.readonly https://api.ebay.com/oauth/api_scope/sell.inventory https://api.ebay.com/oauth/api_scope/sell.account.readonly https://api.ebay.com/oauth/api_scope/sell.account https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly https://api.ebay.com/oauth/api_scope/sell.fulfillment https://api.ebay.com/oauth/api_scope/sell.analytics.readonly https://api.ebay.com/oauth/api_scope/sell.marketplace.insights.readonly https://api.ebay.com/oauth/api_scope/commerce.catalog.readonly https://api.ebay.com/oauth/api_scope/buy.shopping.cart https://api.ebay.com/oauth/api_scope/buy.offer.auction https://api.ebay.com/oauth/api_scope/commerce.identity.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.email.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.phone.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.address.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.name.readonly https://api.ebay.com/oauth/api_scope/commerce.identity.status.readonly https://api.ebay.com/oauth/api_scope/sell.finances https://api.ebay.com/oauth/api_scope/sell.item.draft https://api.ebay.com/oauth/api_scope/sell.payment.dispute https://api.ebay.com/oauth/api_scope/sell.item https://api.ebay.com/oauth/api_scope/sell.reputation https://api.ebay.com/oauth/api_scope/sell.reputation.readonly https://api.ebay.com/oauth/api_scope/commerce.notification.subscription https://api.ebay.com/oauth/api_scope/commerce.notification.subscription.readonly
